import {
    LayoutDashboard,
    List,
    History,
    Calendar,
    Users,
    Bell,
    Shield,
    Activity,
    User,
    Building2,
    Stethoscope,
    HeartHandshake,
    Network,
    Droplet,
    Heart,
    Siren,
    Truck,
    Cpu,
    ShieldCheck,
    Sparkles,
} from "lucide-react"

export const unifiedRoutes = [
    { name: "Network Command", href: "/network", icon: Network },
    { name: "Blood Network", href: "/blood", icon: Droplet },
    { name: "Organ Network", href: "/organ", icon: Heart },
    { name: "Emergency Dispatch", href: "/emergency", icon: Siren },
    { name: "Logistics Center", href: "/logistics", icon: Truck },
    { name: "AI Intelligence", href: "/intelligence", icon: Cpu },
    { name: "Audit & Provenance", href: "/audit", icon: ShieldCheck },
    { name: "Demo Studio", href: "/demo", icon: Sparkles },
]

export const routes = {
    donor: [
        { name: "Network Command", href: "/network", icon: Network },
        { name: "Donor Dashboard", href: "/donor/dashboard", icon: LayoutDashboard },
        { name: "Blood Requests", href: "/donor/requests", icon: List },
        { name: "Donation History", href: "/donor/history", icon: History },
        { name: "My Availability", href: "/donor/availability", icon: Calendar },
        { name: "Profile", href: "/donor/profile", icon: User },
    ],
    hospital: [
        { name: "Network Command", href: "/network", icon: Network },
        { name: "Hospital Console", href: "/hospital/dashboard", icon: LayoutDashboard },
        { name: "Organ Allocation", href: "/organ/review", icon: HeartHandshake },
        { name: "Blood Requests", href: "/hospital/requests", icon: Droplet },
        { name: "Logistics Center", href: "/logistics", icon: Truck },
        { name: "Reservations", href: "/hospital/reservations", icon: Calendar },
        { name: "Alerts", href: "/hospital/alerts", icon: Bell },
        { name: "Profile", href: "/hospital/profile", icon: User },
    ],
    admin: [
        { name: "Network Command", href: "/network", icon: Network },
        { name: "Admin Dashboard", href: "/admin/dashboard", icon: LayoutDashboard },
        { name: "System Operations", href: "/admin/system", icon: Cpu },
        { name: "Intelligence & Sim", href: "/intelligence", icon: Activity },
        { name: "Security & Governance", href: "/admin/security", icon: Shield },
        { name: "Audit & Provenance", href: "/audit", icon: ShieldCheck },
        { name: "Demo Studio", href: "/demo", icon: Sparkles },
    ],
}
