import {
    LayoutDashboard,
    List,
    History,
    Calendar,
    Users,
    Bell,
    Shield,
    Activity,
    User,
    Building2,
    Stethoscope,
    HeartHandshake,
    ShieldCheck,
    FileCheck,
    Heart,
    ClipboardList,
} from "lucide-react"

export const routes = {
    donor: [
        { name: "Dashboard", href: "/donor/dashboard", icon: LayoutDashboard },
        { name: "Organ Opportunities", href: "/donor/organ/opportunities", icon: HeartHandshake },
        { name: "Organ Preferences", href: "/donor/organ/preferences", icon: Heart },
        { name: "Blood Matches", href: "/donor/requests", icon: List },
        { name: "History", href: "/donor/history", icon: History },
        { name: "Availability", href: "/donor/availability", icon: Calendar },
        { name: "Notifications", href: "/donor/notifications", icon: Bell },
        { name: "Profile", href: "/donor/profile", icon: User },
    ],
    hospital: [
        { name: "Dashboard", href: "/hospital/dashboard", icon: LayoutDashboard },
        { name: "Organ Requests", href: "/hospital/organs/requests", icon: ClipboardList },
        { name: "Evaluation Queue", href: "/hospital/organ-evaluations", icon: Stethoscope },
        { name: "Donor Verifications", href: "/hospital/verification", icon: ShieldCheck },
        { name: "Organ Network", href: "/hospital/organs", icon: HeartHandshake },
        { name: "Blood Requests", href: "/hospital/requests", icon: List },
        { name: "Patients", href: "/hospital/patients", icon: Users },
        { name: "Reservations", href: "/hospital/reservations", icon: Calendar },
        { name: "Alerts & Notifications", href: "/hospital/notifications", icon: Bell },
        { name: "Profile", href: "/hospital/profile", icon: User },
    ],
    admin: [
        { name: "Dashboard", href: "/admin/dashboard", icon: LayoutDashboard },
        { name: "Hospitals", href: "/admin/hospitals", icon: Building2 },
        { name: "Donors", href: "/admin/donors", icon: Users },
        { name: "AI Monitor", href: "/admin/ai-monitor", icon: Activity },
        { name: "Audit Logs", href: "/admin/audit-logs", icon: Shield },
        { name: "Profile", href: "/admin/profile", icon: User },
    ],
}
